name: FWTownyCustomUpkeek
version: @version@
main: it.forgottenworld.townycustomupkeep.FWTownyCustomUpkeep
depend: [Towny]
authors: [tigierrei]
api-version: 1.16
description: Customize towns upkeep
website: https://forgottenworld.it
commands:
  ctu:
    permission: ctu.admin
    default: op