name: CustomTownyUpkeep
version: @version@
main: it.forgottenworld.customtownyupkeep.CustomTownyUpkeep
depend: [Towny]
authors: [tigierrei]
description: Customize towns upkeep
website: https://forgottenworld.it
commands:
  ctu:
    permission: ctu.admin
    default: op